<?php

/**
 * BaseProjectCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property varchar $name
 * @property boolean $public
 * @property Doctrine_Collection $Project
 * 
 * @method varchar             getName()    Returns the current record's "name" value
 * @method boolean             getPublic()  Returns the current record's "public" value
 * @method Doctrine_Collection getProject() Returns the current record's "Project" collection
 * @method ProjectCategory     setName()    Sets the current record's "name" value
 * @method ProjectCategory     setPublic()  Sets the current record's "public" value
 * @method ProjectCategory     setProject() Sets the current record's "Project" collection
 * 
 * @package    Kickforce
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProjectCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('force_project_category');
        $this->hasColumn('name', 'varchar', 50, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('public', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Project', array(
             'local' => 'id',
             'foreign' => 'category_id'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => true,
             'fields' => 
             array(
              0 => 'name',
             ),
             'canUpdate' => true,
             ));
        $this->actAs($sluggable0);
    }
}