all:
  upload_dir:  uploads 

  tiny_mce:
    advanced_extract:
      theme: advanced
      language: "ru"
      skin: default
      convert_urls : false
      theme_advanced_toolbar_location: bottom
      theme_advanced_toolbar_align: center
      theme_advanced_buttons1: "paste,pastetext,pasteword,|,bold,italic,underline,strikethrough,|,undo,redo,|,bullist,numlist,|,link,unlink,|,image,insertfile,insertimage,|,code"
      theme_advanced_buttons2: ""
      theme_advanced_buttons3: ""
      plugins : "paste,advimage,imagemanager,filemanager"
      theme_advanced_toolbar_align: left
      mode: "exact" 
    advanced_extract_without_p:
      theme: advanced
      language: "ru"
      skin: default
      convert_urls : false
      theme_advanced_toolbar_location: bottom
      theme_advanced_toolbar_align: center
      theme_advanced_buttons1: "paste,pastetext,pasteword,|,bold,italic,underline,strikethrough,|,undo,redo,|,bullist,numlist,|,link,unlink,|,image,insertfile,insertimage,|,code"
      theme_advanced_buttons2: ""
      theme_advanced_buttons3: ""
      plugins : "paste,advimage,imagemanager,filemanager"
      theme_advanced_toolbar_align: left
      mode: "exact",
      force_br_newlines : "true",
      force_p_newlines : "",
      forced_root_block : ""      
    advanced_content:
      theme: advanced
      language: "ru"
      convert_urls : false
      skin: default
      dialog_type: window
      entity_encoding: raw
      relative_urls: 'false'
      gecko_spellcheck: 'true'
      theme_advanced_buttons1 : "save,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,styleselect,formatselect,fontselect,fontsizeselect",
      theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
      theme_advanced_buttons3 : "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
      theme_advanced_buttons4 : "insertlayer,moveforward,movebackward,absolute,|,styleprops,spellchecker,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,blockquote,      ,|,insertfile,insertimage",
      plugins : "autolink,lists,spellchecker,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,imagemanager,filemanager"
      theme_advanced_toolbar_location: top
      theme_advanced_toolbar_align: left
      theme_advanced_resizing: 'false'  
