<?php

/**
 * AmountTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AmountTable extends Doctrine_Table
{
    
    /**
     * Returns an instance of this class.
     *
     * @return object AmountTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Amount');
    }

}