<?php

/**
 * ProjectCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProjectCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProjectCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProjectCategory');
    }

    /**
    * Returns an instance of this class.
    *
    * @return query all active categories from ProjectCategoryTable 
    */
    public static function getCategoriesQuery()
    {
        return self::getInstance()
            ->createQuery('c')
            ->where('c.public = 1')
            ->orderBy('c.name');
    }

    /**
     * Returns an instance of this class.
     *
     * @return execute all active categories from ProjectCategoryTable  
     */
    public static function getAllCategoriesList()
    {
        $q = self::getCategoriesQuery();

        return $q->execute();
    }

    /**
    * Returns an instance of this class.
    *
    * @return execute all active include projects categories from ProjectCategoryTable  
    */
    public static function getCategoriesList()
    {
        $q = self::getCategoriesQuery()
            ->innerJoin('c.Project p');

        return $q->execute();
    }

    /**
    * Returns an instance of this class.
    *
    * @return category has slug_1 from ProjectCategoryTable  
    */
    public static function getCategory($request)
    {
        $q = self::getCategoriesQuery();
        if($slug = $request->getParameter('slug_1'))
        {
            $q->addWhere('c.slug=?',$slug);
        }

        return $q->fetchOne();
    }
    
}
