# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
settings:
  url:     /settings
  param:   { module: profile, action: index }
profile:
  url:     /profile
  param:   { module: profile, action: profile }
summary:
  url:     /summary
  param:   { module: profile, action: summary }

about:
  url:     /about-us
  param:   { module: content, action: index }

explore:
  url:     /explore
  param:   { module: explore, action: index }
explore_category:
  url:     /explore/:slug_1
  param:   { module: explore, action: index }
explore_show:
  url:     /explore/:slug_1/:slug
  class:   sfDoctrineRoute  
  options: { model:  Project, type: object, method: retrieveProject }
  param:   { module: explore, action: projectShow }
explore_paypal_invest:
  url:     /explore/:slug_1/:slug/invest
  class:   sfDoctrineRoute  
  options: { model:  Project, type: object, method: retrieveProject }
  param:   { module: explore, action: projectPaypalInvest }
  requirements: 
    sf_method: [get,post]
explore_paypal_calculate:
  url:     /explore/:slug_1/:slug/calculate
  class:   sfDoctrineRoute  
  options: { model:  Project, type: object, method: retrieveProject }
  param:   { module: explore, action: projectPaypalCalculate }
  requirements: 
    sf_method: [get]
explore_paypal_payment:
  url:     /explore/:slug_1/:slug/payment
  class:   sfDoctrineRoute  
  options: { model:  Project, type: object, method: retrieveProject }
  param:   { module: explore, action: projectPaypalPayment }
  requirements: 
    sf_method: [get,post]
explore_paypal_result:
  url:     /explore/:slug_1/:slug/result
  class:   sfDoctrineRoute  
  options: { model:  Project, type: object, method: retrieveProject }
  param:   { module: explore, action: projectPaypalResult }
  requirements: 
    sf_method: [get,post]

sf_captchagd:
  url:     /captcha/:key/:reload
  param:   { module: sfCaptchaGD, action: getImage, key: failed, reload: 0 }

homepage:
  url:     /
  param:   { module: main, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:     /:module
  param:   { action: index }

default:
  url:     /:module/:action/*
