generator:
  class: sfDoctrineGenerator
  param:
    model_class:           ProjectStatus
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          project_status
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title:   Project status list
        display:
          - id
          - =name
        actions: []
        batch_actions: []
        object_actions:
          _edit: []	
      filter:
        class: false
      form:    ~
      edit:
        title: Editing status "%%name%%"
        actions:
          _list: []
          _save: []
      new:
        title: Create new status
