generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Project
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          project
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Project list
        display:
          - user
          - =category
          - =status
          - =name
          - created_at
          - updated_at
        actions: []
        batch_actions:
          _delete:  ~
        object_actions:
          _edit: []
        sort: [created_at, desc]
      filter:
        class: false
      form:    ~
      edit:
        title: Editing project "%%name%%"
        actions:
          _list: []
          _save: []
      new:
        title: Create new project
