sfGuardGroup:
  tableName: force_guard_group
sfGuardPermission:
  tableName: force_guard_permission
sfGuardGroupPermission:
  tableName: force_guard_group_permission
sfGuardUser:
  tableName: force_guard_user
sfGuardUserPermission:
  tableName: force_guard_user_permission
sfGuardUserGroup:
  tableName: force_guard_user_group
sfGuardRememberKey:
  tableName: force_guard_remember_key
sfGuardForgotPassword:
  tableName: force_guard_forgot_password
